services:
  directusfreeipasyncer:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/srv/data
    networks:
      - directus_directus_internal

networks:
  directus_directus_internal:
    external: true